name: Create and Deploy Lambda 
on:  
  push:   
    branches:  
    - development
    - ab-42-integrateLambda
    - kj-ab-42-integrateLambda
 
env: 
  GITHUB_ACTOR: ${GITHUB_ACTOR}

jobs:  
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "ACTOR_INITIALS=$(echo $GITHUB_ACTOR | cut -c 1-2)" >> $GITHUB_ENV
      - name: Show Initials
        run: echo $"{{env.ACTOR_INITIALS}}"
      - uses: actions/checkout@v2  
      - name: Configure AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v1 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - run: . ./.github/scripts/makeLambdaFunction.bash ${{env.ACTOR_INITIALS}} us-west-2 #pass parameters
        shell: bash
      - run: |
          echo "${{env.FUNCTION_NAME}}"
      - name: Deploy code to Lambda Function
        run: |
          zip -j deploy.zip ./* 
          aws lambda update-function-code --function-name=${{env.FUNCTION_NAME}} --zip-file=fileb://deploy.zip