name: S3-deploy

on:
  push:
    branches:
      - "development"
      - "pt-s3action"
env:
  GITHUB_ACTOR: ${GITHUB_ACTOR}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Set env
        run: echo "ACTOR_INITIALS=$(echo $GITHUB_ACTOR | cut -c 1-4)" >> $GITHUB_ENV
      - name: Show Initials
        run: echo ${{ env.ACTOR_INITIALS }}
      - uses: actions/checkout@v1
      - run: npm install
        working-directory: ./frontend/floop_feedback
      - run: npm install mini-css-extract-plugin@~2.4.5
        working-directory: ./frontend/floop_feedback
      - run: npm run build
        working-directory: ./frontend/floop_feedback
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'build'
      - run: . ./.github/scripts/makeReactBucket.bash ${{ env.ACTOR_INITIALS }} us-west-2
        shell: bash
      - run: |
          echo "http://${{ env.BUCKET_NAME }}.s3-website-${{ env.AWS_REGION }}.amazonaws.com"
      - name: Deploy app build to S3 bucket
        working-directory: ./frontend/floop_feedback
        run: aws s3 sync ./build s3://${{ env.BUCKET_NAME }}